add Main, Person. List, Set and Map handlers
brav3luk3/time-comparison-of-data-structures pull request #1
Opened 2023-05-19 12:17 UTC by brav3luk3

2023-05-19 12:34 UTC, captim requested changes

2023-05-19 12:34 UTC, captim commented on src/main/ListHandler.java
> +    private static int rnd(int max) {
normal method names pls

2023-05-19 12:34 UTC, captim commented on src/main/ListHandler.java
> +    private String listStatus() {
rename to listType()

2023-05-19 12:34 UTC, captim commented on src/main/Main.java
> +        ListHandler lin = new ListHandler(elements, false);
you can use one variable "listHandler" and reuse it for second list
ListHandler listHandler = new ListHandler(elements, true);
...
listHandler = new ListHandler(elements, false);
...

2023-05-19 12:34 UTC, captim commented on src/main/Main.java
> +        SetHandler treeSet = new SetHandler(elements, false);
same as above

2023-05-19 12:34 UTC, captim commented on src/main/Main.java
> +        MapHandler treeMap = new MapHandler(elements, false);
same as above

2023-05-19 12:34 UTC, captim commented on src/main/Main.java
> +        arr.get(8000);
create variable for 500 and 8000 to use it in these methods

2023-05-19 12:34 UTC, captim commented on src/main/MapHandler.java
> +    private Person person;
Useless field

2023-05-19 12:34 UTC, captim commented on src/main/MapHandler.java
> +    }
repeated methods in handlers. maybe it's better to create abstract class

2023-05-19 12:34 UTC, captim commented on src/main/MapHandler.java
> +    }
... with this methods

2023-05-19 12:34 UTC, captim commented on src/main/MapHandler.java
> +    public void remove(int DelElem) {
normal names for variables (deleteElements)
*Java code convention

2023-05-19 12:34 UTC, captim commented on src/main/MapHandler.java
> +    public void get(int getElem) {
same as above

2023-05-19 12:34 UTC, captim commented on src/main/SetHandler.java
> +    public void remove(int DelElem) {
same as above

2023-05-19 12:34 UTC, captim commented on src/main/SetHandler.java
> +    public void get(int getElem) {
same as above

2023-05-22 14:20 UTC, brav3luk3 commented
An abstract class has been created. The MapHandler and ListHandler classes are extended from it.
Methods randomNumber, randomChar and getRandomElement have been changed to a separate class.

2023-05-22 14:25 UTC, captim approved these changes

2023-05-25 13:30 UTC, merged